Add memory limit section to PHP
CleverCloud/doc.clever-cloud.com pull request #553
Opened 2021-03-17 16:08 UTC by gaelreyrol

I added a new section to describe how php memory limit is defined and how a user can change it.

2021-03-26 11:38 UTC, BlackYoup requested changes

2021-03-26 11:38 UTC, BlackYoup commented on deploy/application/php/php-apps.md
> +## Memory Limit
This section should be put later in the documentation, maybe after "Configure your PHP application"? Maybe it doesn't even require a `h2` title, just another sub-section.

2021-03-26 11:38 UTC, BlackYoup commented on deploy/application/php/php-apps.md
> +A smaller part of your application's memory is defined as the memory limit to allow workers to run efficiently, here is the memory limit for each flavor:
I'm not sure to really understand what's this limit is when I read this sentence. I feel like this says `we only use 2048M of memory even though you have 32GB in total`. But that may be only me.

IIRC, this is the memory limit of each worker spawned by the `php-fpm` process.

2021-04-01 18:42 UTC, gaelreyrol commented
It should be better ?

2021-04-07 10:22 UTC, merged

2021-04-07 10:22 UTC, BlackYoup commented
Thanks :)