Warn about Bintray ending
CleverCloud/doc.clever-cloud.com pull request #573
Opened 2021-04-12 16:05 UTC by gaelreyrol

Before complete migration, we should warm users about Bintray's end as described in #572 and https://github.com/CleverCloud/clever-tools/issues/454.

I've added warning alerts alongside distributions using Bintray to install our cli.

2021-04-12 17:47 UTC, BlackYoup requested changes
Small change but other than that, it looks good!

2021-04-12 17:47 UTC, BlackYoup commented on reference/clever-tools/getting_started.md
> +<p>Bintray is ending on 1st May, we will migrate hosting as soon as possible.</p>
You should specify the year here. And the date should be written `May 1st 2021.`

2021-04-13 09:22 UTC, hsablonniere commented
Thanks @gaelreyrol for this :clap:
This page is mostly a copy of this https://github.com/CleverCloud/clever-tools/blob/master/README.md
so I guest we should update both.

2021-04-13 09:31 UTC, gaelreyrol commented
> This page is mostly a copy of this https://github.com/CleverCloud/clever-tools/blob/master/README.md
> so I guest we should update both.

Do you want me to it too ? :slightly_smiling_face: @hsablonniere

2021-04-13 18:17 UTC, merged