Remove duplicated sections in Fluentd tutorial
CleverCloud/doc.clever-cloud.com pull request #637
Opened 2021-07-13 09:10 UTC by gaelreyrol

Close #589.

2021-08-03 13:27 UTC, BlackYoup commented on deploy/application/docker/tutorials/fluentd.md
> +{{< alert "info" "Why I can't just use Ruby runtime ?" >}}
```suggestion
{{< alert "info" "Why can't I use the Ruby runtime ?" >}}
```

I had a hard time figuring out that the "ruby runtime" here is a ruby application. Maybe we could replace `the Ruby runtime` by `a Ruby application`? I don't know

2021-08-09 12:34 UTC, BlackYoup requested changes
Last small modification but other than that, ok :+1:

2021-08-09 12:34 UTC, BlackYoup commented on deploy/application/docker/tutorials/fluentd.md
> +{{< alert "info" "Why I can't use the Ruby application ?" >}}
```suggestion
{{< alert "info" "Why can't I use the Ruby application?" >}}
```

2021-12-02 11:19 UTC, gaelreyrol commented on deploy/application/docker/tutorials/fluentd.md
> +{{< alert "info" "Why I can't use the Ruby application ?" >}}
Fixed

2021-12-08 09:40 UTC, BlackYoup approved these changes

2021-12-08 11:08 UTC, merged