feat(prometheus): add basic_auth and response timeout environment var
CleverCloud/doc.clever-cloud.com pull request #650
Opened 2021-07-23 07:31 UTC by aurrelhebert

2021-07-27 06:14 UTC, gaelreyrol commented on administrate/metrics/overview.md
> +- `CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT_SECONDS`: Define the timout in seconds to collect the application metrics. This value **must** be below 60 seconds as data are collected every minutes.
```suggestion
- `CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT`: Define the timout in seconds to collect the application metrics. This value **must** be below 60 seconds as data are collected every minutes. 
```

2021-07-27 06:14 UTC, gaelreyrol commented on reference/reference-environment-variables.md
> +|[CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT_SECONDS]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the timout in seconds to collect the application metrics. This valu
```suggestion
|[CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the timout in seconds to collect the application metrics. This value **must** be below 60 seconds as data are collected every minutes | `3` |
```

2021-07-27 06:14 UTC, gaelreyrol commented on reference/reference-environment-variables.md
> +|[CC_METRICS_PROMETHEUS_PASSWORD]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the password for the basic auth of the Prometheus endpoint| `None` |
```suggestion
|[CC_METRICS_PROMETHEUS_PASSWORD]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the password for the basic auth of the Prometheus endpoint|  |
```

2021-07-27 06:14 UTC, gaelreyrol commented on reference/reference-environment-variables.md
> +|[CC_METRICS_PROMETHEUS_USER]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the user for the basic auth of the Prometheus endpoint | `None` |
```suggestion
|[CC_METRICS_PROMETHEUS_USER]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the user for the basic auth of the Prometheus endpoint |  |
```

2021-07-27 06:14 UTC, gaelreyrol commented on reference/reference-environment-variables.md
> +|[CC_METRICS_PROMETHEUS_USER]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the user for the basic auth of the Prometheus endpoint | `None` |
For now if the value is not defined by default we leave the field empty.

2021-08-03 13:02 UTC, BlackYoup requested changes
Few typos, other than that, isok

2021-08-03 13:02 UTC, BlackYoup commented on administrate/metrics/overview.md
> +- `CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT`: Define the timout in seconds to collect the application metrics. This value **must** be below 60 seconds as data are collected every minutes.
```suggestion
- `CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT`: Define the timeout in seconds to collect the application metrics. This value **must** be below 60 seconds as data are collected every minutes. 
```

2021-08-03 13:02 UTC, BlackYoup commented on reference/reference-environment-variables.md
> +|[CC_METRICS_PROMETHEUS_PASSWORD]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the password for the basic auth of the Prometheus endpoint| |
```suggestion
|[CC_METRICS_PROMETHEUS_PASSWORD]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the password for the basic auth of the Prometheus endpoint | |
```

2021-08-03 13:02 UTC, BlackYoup commented on reference/reference-environment-variables.md
> +|[CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the timout in seconds to collect the application metrics. This value **must
```suggestion
|[CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT]({{< ref "administrate/metrics/overview.md#publish-your-own-metrics" >}}) | Define the timeout in seconds to collect the application metrics. This value **must** be below 60 seconds as data are collected every minutes | `3` |
```

2021-08-16 08:34 UTC, gaelreyrol approved these changes

2021-08-16 10:27 UTC, merged