Draft: Jenkins doc
CleverCloud/doc.clever-cloud.com pull request #671
Opened 2021-08-23 15:52 UTC by BlackYoup

Here is a first version of the new Jenkins documentation, there might still be some things to improve.

Preview link: https://cc-doc-preview-jenkins-doc.cleverapps.io/doc/deploy/addon/jenkins/

Feedback is welcome :)

2021-09-27 17:31 UTC, gaelreyrol requested changes
Do you think we could provide a `Jenkinsfile` section with an example ?

2021-09-27 17:31 UTC, gaelreyrol commented on deploy/addon/jenkins.md
> +As of today, only runners on Clever Cloud docker applications are supported. The docker image you provide **must** contain the Jenkins Inbound agent.
```suggestion
As of today, only runners on Clever Cloud Docker applications are supported. The Docker image you provide **must** contain the Jenkins Inbound agent.
```

2021-09-27 17:31 UTC, gaelreyrol commented on deploy/addon/jenkins.md
> +By default, Jenkins provides a few docker images that embed this agent. The agent will then connect to Jenkins to receive jobs orders.
```suggestion
By default, Jenkins provides a few Docker images that embed this agent. The agent will then connect to Jenkins to receive jobs orders.
```

2021-09-27 17:31 UTC, gaelreyrol commented on deploy/addon/jenkins.md
> +You can find more details on the default [Jenkins Inbout agent](https://hub.docker.com/r/jenkins/inbound-agent/) docker image. Jenkins also
```suggestion
You can find more details on the default [Jenkins Inbout agent](https://hub.docker.com/r/jenkins/inbound-agent/) Docker image. Jenkins also
```

2021-09-28 10:26 UTC, BlackYoup commented on deploy/addon/jenkins.md
> +The Weekly version isn't available during the creation, yet, but if you ever need it, feel free to ask our support team about it.
> Is there any procedure to handle this internally ?

Not really no, using the weekly version would mean to correctly support it. Moving from an LTS version to a weekly version is discouraged.

2021-09-28 10:30 UTC, BlackYoup commented on deploy/addon/jenkins.md
> +3. Select the plan you need.
Why? Do you want to list them here?

2021-09-28 10:30 UTC, BlackYoup commented
> Do you think we could provide a Jenkinsfile section with an example ?

Yes, we probably could, I'll have to get one.

2021-09-28 13:22 UTC, gaelreyrol commented on deploy/addon/jenkins.md
> +3. Select the plan you need.
I think it would be useful to provide a link to those plans or add a section at the bottom of the page as for the other add-ons.

2021-09-28 13:23 UTC, gaelreyrol commented on deploy/addon/jenkins.md
> +The Weekly version isn't available during the creation, yet, but if you ever need it, feel free to ask our support team about it.
Alright

2021-09-28 16:45 UTC, BlackYoup commented on deploy/addon/jenkins.md
> +3. Select the plan you need.
Yes, a pricing component should be there soon but in the meantime, you're right, I could describe the pricing in a dedicated section.

2021-09-30 11:43 UTC, merged