Add missing PHP extensions
CleverCloud/doc.clever-cloud.com pull request #707
Opened 2021-11-17 10:50 UTC by gaelreyrol

Some PHP extensions to enable were missing.

2021-11-29 09:51 UTC, BlackYoup requested changes

2021-11-29 09:51 UTC, BlackYoup commented on partials/language-specific-deploy/php.md
> +    GnuPG is an extension that provides methods to interact with
To interact with what? :)

2021-12-02 11:18 UTC, gaelreyrol commented on partials/language-specific-deploy/php.md
> +    GnuPG is an extension that provides methods to interact with
Fixed

2021-12-08 09:40 UTC, BlackYoup approved these changes

2021-12-08 11:07 UTC, merged