add Matomo addon
CleverCloud/doc.clever-cloud.com pull request #754
Opened 2022-04-09 10:44 UTC by StevenLeRoux

2022-04-11 09:31 UTC, cnivolle commented on deploy/addon/matomo.md
> +{{< image "/images/jenkins/full-dashboard.png" "Jenkins Dashboard" >}}
We need to update the screenshot.

2022-04-11 12:44 UTC, cnivolle requested changes
The screenshot show a jenkins-related image. It should be an example of a Matomo product.

2022-04-28 15:18 UTC, hsablonniere commented on deploy/addon/matomo.md
> +<cc-smart-container context='{"productId": "PHP", "addonFeatures": ["cpu", "memory", "disk-size", "has-logs", "has-metrics"]}'>
* `PHP` => `php`
* `addonFeatures` can be removed for PHP

2022-04-28 15:18 UTC, hsablonniere commented on deploy/addon/matomo.md
> +  <cc-pricing-product mode="runtime" action="none" temporality='[{"type":"minute","digits":5}, {"type": "1000-minutes","digits": 2}]'>
* We can remove the `temporality` attribute (this will fallback on day and 30 days)

2022-04-28 15:18 UTC, hsablonniere commented on deploy/addon/matomo.md
> +  <cc-pricing-product mode="runtime" action="none" temporality='[{"type":"minute","digits":5}, {"type": "1000-minutes","digits": 2}]'>
We can remove the temporality attribute (this will fallback on day and 30 days)

2022-04-28 15:20 UTC, hsablonniere commented
@cnivolle Do you know how to use the product pricing blocks with the Hugo shortcodes instead of raw HTML?

2023-04-24 15:17 UTC, closed without merging