add customize kibana documentation
CleverCloud/doc.clever-cloud.com pull request #825
Opened 2023-02-03 15:14 UTC by sebartyr

How to customize Kibana configuration

2023-02-10 17:05 UTC, judu requested changes

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +Kibana can be enabled at the add-on creation. Choose "Create an add-on" > "Elastic Stack". Select your plan, applications which will use the Elasctic Stack and name the add-on. On the options for the
```suggestion
Kibana can be enabled at the add-on creation. Choose "Create an add-on" > "Elastic Stack". Select your plan, applications which will use the Elastic Stack and name the add-on. On the "options" step, enable Kibana. Then, confirm the options and your add-on will start with a Kibana instance.
```

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +### Customize Kibana configuration file
```suggestion
### Customize the Kibana configuration file
```

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +To modify this default configuration ([Configuration file for Kibana 8.3.3](https://api.clever-cloud.com/v2/providers/es-addon/kibana-setup/8.3.3)), you need to host your own config file (we strongly
```suggestion
To modify this default configuration ([Configuration file for Kibana 8.3.3](https://api.clever-cloud.com/v2/providers/es-addon/kibana-setup/8.3.3)), you need to host your own config file (we strongly recommend [Cellar](/deploy/addon/cellar)).
```

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +Check other available configuration file on [Github](https://github.com/sebartyr/custom-kibana-config)
Push this to a Clever Cloud repository.

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +To disable SSO authentication and use instead elastic users, you need to modify the configuration file of Kibana and `CC_PRE_RUN_HOOK` in environment variables.
```suggestion
To disable SSO authentication and use elastic users instead, you need to modify Kibana's configuration file and `CC_PRE_RUN_HOOK` in environment variables.
```

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +`CC_PRE_RUN_HOOK` = `curl https://raw.githubusercontent.com/sebartyr/custom-kibana-config/master/no-sso-8.3.3 | sh`
Link to the Clever Cloud repository.

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +Remember, you need to ask Clever Cloud Support team to enable superuser permissions to your user. Then, you could add some additional users with Kibana.
```suggestion
Remember, you need to ask Clever Cloud Support team to grant superuser permissions to your user. After that, you will be able to add additional users via Kibana.
```

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +## Deploy Kibana at localhost
```suggestion
## Deploy Kibana on localhost
```

2023-02-10 17:05 UTC, judu commented on deploy/addon/elastic/kibana.md
> +- Go on Kibana through the dedicated [local address](http://localhost:5601)
```suggestion
- Go to Kibana through the dedicated [local address](http://localhost:5601)
```

2023-02-10 17:43 UTC, sebartyr commented on deploy/addon/elastic/kibana.md
> +`CC_PRE_RUN_HOOK` = `curl https://raw.githubusercontent.com/sebartyr/custom-kibana-config/master/no-sso-8.3.3 | sh`
```suggestion
`CC_PRE_RUN_HOOK` = `curl https://raw.githubusercontent.com/CleverCloud/custom-kibana-config/master/no-sso-8.3.3 | sh`
```

2023-02-10 17:45 UTC, sebartyr commented on deploy/addon/elastic/kibana.md
> +Follow these steps :
```suggestion
## Deploy Kibana on localhost

The Kibana version should match with the ElasticSearch version.

Follow these steps :
```

2023-02-23 01:32 UTC, sebartyr commented on deploy/addon/elastic/kibana.md
> +`CC_PRE_RUN_HOOK` = `curl https://raw.githubusercontent.com/CleverCloud/custom-kibana-config/master/no-sso-8.3.3 | sh`
```suggestion
`CC_PRE_RUN_HOOK` = `curl https://raw.githubusercontent.com/CleverCloud/custom-kibana-config/master/8.3.3/no-sso-8.3.3 | sh`
```

2023-02-23 01:34 UTC, merged